/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TripStepRouteImport } from './routes/trip.$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TripStepRoute = TripStepRouteImport.update({
  id: '/trip/$step',
  path: '/trip/$step',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/trip/$step': typeof TripStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/trip/$step': typeof TripStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer': typeof BuyerRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/trip/$step': typeof TripStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer'
    | '/login'
    | '/owner'
    | '/profile'
    | '/signup'
    | '/trip/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyer'
    | '/login'
    | '/owner'
    | '/profile'
    | '/signup'
    | '/trip/$step'
  id:
    | '__root__'
    | '/'
    | '/buyer'
    | '/login'
    | '/owner'
    | '/profile'
    | '/signup'
    | '/trip/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerRoute: typeof BuyerRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TripStepRoute: typeof TripStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$step': {
      id: '/trip/$step'
      path: '/trip/$step'
      fullPath: '/trip/$step'
      preLoaderRoute: typeof TripStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerRoute: BuyerRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TripStepRoute: TripStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
