"""Fit the three buyer dataset models offline and write fixtures/buyer_models.json.

    python scripts/train_buyer_models.py          # trains, prints metrics, writes the fixture
    python scripts/train_buyer_models.py --dry    # trains and prints, writes nothing

Needs scikit-learn and numpy from requirements-dev.txt. The API never imports them: the fitted
parameters go into the fixture and app/buyer_models.py scores them with plain arithmetic. The one
exception is the isolation forest, which is also saved to models/anomaly_isolation_forest.joblib
for scoring trips created after training. That file is not committed; rerun this script to make it.

Everything is fitted on simulated data. Read the honest notes it prints before quoting any number.
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import joblib  # noqa: E402
import numpy as np  # noqa: E402
import sklearn  # noqa: E402
from sklearn.ensemble import GradientBoostingClassifier, IsolationForest  # noqa: E402
from sklearn.linear_model import LinearRegression, LogisticRegression  # noqa: E402
from sklearn.metrics import mean_absolute_error, r2_score, roc_auc_score  # noqa: E402
from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split  # noqa: E402
from sklearn.preprocessing import StandardScaler  # noqa: E402

from app import buyer_models as bm  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DATASET = ROOT / "fixtures" / "buyer_dataset.json"
OUT = ROOT / "fixtures" / "buyer_models.json"
SEED = 20261004
CONTAMINATION = 0.15        # flag roughly the most unusual one in seven trips
LIBRARY = f"scikit-learn {sklearn.__version__}"

ANOMALY_NOTES = (
    "Unsupervised IsolationForest over per-trip driving features, including event rates. It learns "
    "which trips sit furthest from the rest of this dataset and flags about one in seven. A flag "
    "means unusual for this simulated fleet, not unsafe. There is no ground truth to score it "
    "against, so no accuracy is reported."
)
RISK_NOTES = (
    "Gradient boosting estimating the chance a trip contains a Review severity event, from miles, "
    "duration, average speed, energy rate and start hour. It is given no event counts and no "
    "severities, so it cannot read the answer off its own label. A driver's score is the mean "
    "predicted chance across their trips, shown on a 0 to 100 scale. "
    "A logistic model was tried first and rejected: in this fixture every non-event feature rises "
    "with the driver index while the Review events do not, so the straight line put a driver with "
    "no Review events at the top. Gradient boosting can bend, so it separates them. "
    "Honest limits: the sample is 48 simulated trips with 16 positives, cross-validated rather than "
    "held out once because that is too few to split and believe. Start hour and energy rate are both "
    "deterministic functions of which driver drove in this fixture, so the model can identify "
    "drivers indirectly. It is not a validated safety score and must not be used to judge a real "
    "person."
)
ENERGY_NOTES = (
    "Ordinary least squares predicting kWh per mile from miles, duration, average speed, event "
    "rates and start hour, with energy itself held out of the inputs. Fitted on a random 70 percent "
    "of the 48 simulated trips and scored on the remaining 30 percent. Honest limits: the energy "
    "figures in this simulated fixture are generated by a fixed formula, so a strong fit measures "
    "how well the regression recovers that formula, not how well it would predict real consumption "
    "from a real car."
)


def load_rows() -> tuple[list[dict], list[dict]]:
    trips = json.loads(DATASET.read_text(encoding="utf-8"))["demoTrips"]
    rows = []
    for trip in trips:
        features = bm.features_for(trip, trip["events"])
        rows.append({"trip_id": trip["id"], "driver_id": trip["driverId"], **features})
    return trips, rows


def matrix(rows: list[dict], names: list[str]) -> np.ndarray:
    return np.array([[float(r[n]) for n in names] for r in rows], dtype=float)


def train_anomaly(rows: list[dict]) -> tuple[dict, list[float], list[bool]]:
    x = matrix(rows, bm.ANOMALY_FEATURES)
    model = IsolationForest(n_estimators=300, contamination=CONTAMINATION, random_state=SEED)
    model.fit(x)
    scores = [round(float(s), 6) for s in model.score_samples(x)]
    flagged = [bool(p == -1) for p in model.predict(x)]
    joblib.dump({"model": model, "features": bm.ANOMALY_FEATURES}, _forest_path())
    run = {
        "name": bm.ANOMALY, "kind": "anomaly_detection", "library": LIBRARY,
        "features": bm.ANOMALY_FEATURES, "random_seed": SEED,
        "metrics": {"flagged": sum(flagged), "trips": len(rows),
                    "contamination": CONTAMINATION,
                    "score_min": min(scores), "score_max": max(scores),
                    "note": "unsupervised, so no accuracy can be reported"},
        "params": {"kind": "isolation_forest", "scored_at_runtime_from": str(_forest_path().name),
                   "features": bm.ANOMALY_FEATURES},
        "notes": ANOMALY_NOTES,
    }
    return run, scores, flagged


def _forest_path() -> Path:
    bm.MODEL_DIR.mkdir(parents=True, exist_ok=True)
    return bm.FOREST_FILE


def _export_tree(estimator) -> dict:
    """One fitted regression tree as plain lists, so runtime can walk it without scikit-learn."""
    tree = estimator.tree_
    return {"feature": [int(f) for f in tree.feature],
            "threshold": [round(float(t), 10) for t in tree.threshold],
            "left": [int(i) for i in tree.children_left],
            "right": [int(i) for i in tree.children_right],
            "value": [round(float(v.ravel()[0]), 10) for v in tree.value]}


def _export_boosting(model, x: np.ndarray) -> dict:
    """Trees plus the constant starting score, recovered from the model rather than a private API."""
    trees = [_export_tree(stage[0]) for stage in model.estimators_]
    params = {"kind": "gradient_boosting", "features": bm.RISK_FEATURES,
              "learning_rate": float(model.learning_rate), "trees": trees, "init_raw": 0.0}
    from_trees = np.array([model.learning_rate * sum(bm._leaf_value(t, list(row)) for t in trees)
                           for row in x])
    offsets = model.decision_function(x) - from_trees
    assert float(offsets.std()) < 1e-9, "the starting score must be one constant"
    params["init_raw"] = round(float(offsets.mean()), 10)
    return params


def train_risk(rows: list[dict]) -> tuple[dict, list[float], list[dict]]:
    x = matrix(rows, bm.RISK_FEATURES)
    y = np.array([1 if r["has_review_event"] else 0 for r in rows], dtype=int)
    model = GradientBoostingClassifier(random_state=SEED)
    model.fit(x, y)

    # 48 trips is far too few to hold out once and believe the number, so report cross-validated
    # performance over the whole set instead of a single lucky split.
    folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
    cv_probability = cross_val_predict(GradientBoostingClassifier(random_state=SEED),
                                       x, y, cv=folds, method="predict_proba")[:, 1]
    cv_auc = float(roc_auc_score(y, cv_probability))
    cv_accuracy = float(((cv_probability >= 0.5).astype(int) == y).mean())
    exact = [float(p) for p in model.predict_proba(x)[:, 1]]
    probability = [round(p, 6) for p in exact]

    # A logistic baseline, reported so the choice of model is visible rather than asserted.
    scaler = StandardScaler().fit(x)
    baseline_cv = cross_val_predict(LogisticRegression(max_iter=2000, random_state=SEED),
                                    scaler.transform(x), y, cv=folds, method="predict_proba")[:, 1]
    baseline_auc = float(roc_auc_score(y, baseline_cv))

    exported = _export_boosting(model, x)
    # The fixture is only useful if pure-Python scoring reproduces scikit-learn exactly.
    for row, expected in zip(rows, exact):
        got = bm.risk_probability(row, exported)
        assert got is not None and abs(got - expected) < 1e-9, f"export mismatch on {row['trip_id']}"

    by_driver: dict[str, list[float]] = {}
    for row, p in zip(rows, probability):
        by_driver.setdefault(row["driver_id"], []).append(p)
    drivers = [{"driver_id": d, "trips": len(ps),
                "mean_probability": round(sum(ps) / len(ps), 6),
                "risk_score": bm.risk_score_from_probability(sum(ps) / len(ps))}
               for d, ps in sorted(by_driver.items())]

    run = {
        "name": bm.RISK, "kind": "driver_risk", "library": LIBRARY,
        "features": bm.RISK_FEATURES, "random_seed": SEED,
        "metrics": {"model": "GradientBoostingClassifier", "trips": len(rows),
                    "positives": int(y.sum()), "majority_class_rate": round(1 - float(y.mean()), 4),
                    "cv_folds": 5, "cv_roc_auc": round(cv_auc, 4),
                    "cv_accuracy": round(cv_accuracy, 4),
                    "logistic_baseline_cv_roc_auc": round(baseline_auc, 4),
                    "note": "cross-validated on 48 simulated trips; not validated on real driving"},
        "params": exported,
        "notes": RISK_NOTES,
    }
    return run, probability, drivers


def train_energy(rows: list[dict]) -> tuple[dict, list[float]]:
    x = matrix(rows, bm.ENERGY_FEATURES)
    y = np.array([float(r["kwh_per_mi"]) for r in rows], dtype=float)
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=SEED)
    model = LinearRegression().fit(x_train, y_train)
    held_out = model.predict(x_test)
    mae = float(mean_absolute_error(y_test, held_out))
    r2 = float(r2_score(y_test, held_out))
    predicted = [round(max(0.0, float(p)), 6) for p in model.predict(x)]
    run = {
        "name": bm.ENERGY, "kind": "energy_regression", "library": LIBRARY,
        "features": bm.ENERGY_FEATURES, "random_seed": SEED,
        "metrics": {"target": "kwh_per_mi", "train_rows": len(x_train), "test_rows": len(x_test),
                    "test_mae": round(mae, 6), "test_r2": round(r2, 4),
                    "mean_actual_kwh_per_mi": round(float(y.mean()), 6),
                    "note": "held-out 30 percent of 48 simulated trips"},
        "params": {"kind": "linear_regression", "features": bm.ENERGY_FEATURES,
                   "coefficients": [round(float(c), 10) for c in model.coef_],
                   "intercept": round(float(model.intercept_), 10)},
        "notes": ENERGY_NOTES,
    }
    return run, predicted


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry", action="store_true", help="train and print without writing the fixture")
    args = parser.parse_args()

    trips, rows = load_rows()
    print(f"dataset: {len(rows)} simulated trips, {sum(r['hard_brakes'] + r['rapid_accels'] + r['sharp_turns'] for r in rows)} events, "
          f"{len({r['driver_id'] for r in rows})} drivers")
    print(f"seed {SEED}, {LIBRARY}\n")

    anomaly_run, anomaly_scores, anomaly_flagged = train_anomaly(rows)
    risk_run, risk_probability, drivers = train_risk(rows)
    energy_run, predicted = train_energy(rows)

    for run in (anomaly_run, risk_run, energy_run):
        print(f"{run['name']}: {json.dumps(run['metrics'])}")
    print("\ndriver risk (0 to 100, mean predicted chance of a Review event):")
    for d in sorted(drivers, key=lambda d: -d["risk_score"]):
        print(f"  {d['driver_id']}  score {d['risk_score']:>3}  over {d['trips']} trips")

    scores = []
    for row, a_score, a_flag, p, pred in zip(rows, anomaly_scores, anomaly_flagged,
                                             risk_probability, predicted):
        scores.append({
            "trip_id": row["trip_id"], "driver_id": row["driver_id"],
            "features": {name: row[name] for name in sorted(set(
                bm.ANOMALY_FEATURES + bm.RISK_FEATURES + bm.ENERGY_FEATURES))},
            "anomaly_score": a_score, "anomaly_flagged": a_flag,
            "risk_probability": p,
            "predicted_kwh_per_mi": pred, "actual_kwh_per_mi": row["kwh_per_mi"],
            "scored_by": "fixture",
        })

    bundle = {
        "generated_by": "backend/scripts/train_buyer_models.py",
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "dataset": "fixtures/buyer_dataset.json",
        "dataset_rows": len(rows),
        "simulated": True,
        "validated": False,
        "disclaimer": ("Models trained on simulated data. No real telemetry was used and no accuracy"
                       " claim applies outside this fixture. Not a validated safety score."),
        "runs": [anomaly_run, risk_run, energy_run],
        "trip_scores": scores,
        "driver_risk": drivers,
    }
    if args.dry:
        print("\n--dry: nothing written")
        return 0
    OUT.write_text(json.dumps(bundle, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(ROOT.parent)} ({len(scores)} trip scores, {len(drivers)} drivers)")
    print(f"wrote {bm.FOREST_FILE.relative_to(ROOT.parent)} (not committed; rerun this script to recreate)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
